version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    
    command: -p $DB_PORT
    ports:
      - $DB_PORT:$DB_PORT
    container_name: database
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    container_name: web
    restart: always    
    depends_on:
      - db
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"



  
volumes:
  postgres_data:
